version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    labels:
      - 📦 dependencies
    directory: "/"
    commit-message:
      prefix: "chore(deps)[github-actions]"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    labels:
      - 📦 dependencies
    directory: "/"
    commit-message:
      prefix: "chore(deps)[npm]"
    schedule:
      interval: "weekly"
    reviewers:
      - "dev-AshishRanjan"
    groups:
      types-dependencies:
        patterns:
          - "@types/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      pre-commit-dependencies:
        patterns:
          - "husky"
          - "prettier"
        update-types:
          - "major"
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"
